### ISSUE TITLE
unranked data entries avoid processing of our sds

### ISSUE THREAD

**Issue by biodivAtlasAT** [AtlasOfLivingAustralia/sds#31]
For some reason, names that are ranked genus (and are ranked as genus also in the BIE) aren't recognised and the rank is put to "UNRANKED" (see Screenshot 1). I think we've found the issue but now we are not sure how to deal with it, as I guess it is nothing we can correct: We think it has to do with the name-parser from gbif (https://www.gbif.org/tools/name-parser) - there, no rank is listed under "rankMarker" (Screenshot2). For our example "Crocus L." the rankMarker should be GENUS. Any advice/ideas/etc.

![screenshot_1](https://user-images.githubusercontent.com/56541520/99069308-655c0a00-25ae-11eb-908a-d3b3b11a24c2.png)
![screenshot_2](https://user-images.githubusercontent.com/56541520/99069309-65f4a080-25ae-11eb-9f1a-baa979cba415.png)

**Comment by Sherrin-ALA** [comment]
The GBIF name parser cannot distinguish between taxon ranks above species (e.g. genus, family), and the code defaults the value to "UNRANKED"

This can cause issues with name matching when the sensitive species data xml file is parsed by the SDS web service when trying to resolve homonyms.

The proposed solution is to check for the existence of a taxonRank column in the source list, and use any value supplied there in preference to the GBIF Name Parser.
