### ISSUE TITLE
galah SDS API - issue with user roles and table misalignment

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/sds#51]
(Reported by user - Thurs 22 Feb)

User noticed an issue with Galah API functioning, where tables being returned by the R galah package are returning misaligned, e.g. event dates are returning in the latitude column.

The first time they saw this was a few weeks ago, so it shouldn't be related to the recent names update.
The issue happens to one user's account but not another. It appears that SDS roles are implemented even though there hasn't been authentication via Galah. 

- Discussed on ALA slack from here, on Thursday 22nd https://atlaslivingaustralia.slack.com/archives/CDFRZFR0F/p1708555222267319

-  See also this thread from Monday 26th  https://atlaslivingaustralia.slack.com/archives/CDFRZFR0F/p1708906045878949?thread_ts=1708559696.238579&cid=CDFRZFR0F

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/883
